all:
  hosts:
    master:
      ansible_host: 10.10.10.133
      ansible_user: roman  # или root, или твой юзер
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519.pub  # путь к твоему SSH ключу
    worker1:
      ansible_host: 10.10.10.187
      ansible_user: roman
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519.pub
    # Если у тебя 3 ноды
    # worker2:
    #   ansible_host: 10.10.10.188
    #   ansible_user: ubuntu
    #   ansible_ssh_private_key_file: ~/.ssh/id_rsa

# Группы для Kubespray
kube_control_plane:
  hosts:
    master:

kube_node:
  hosts:
    master:
    worker1: